export WORKON_HOME=~/.virtualenvs
#source /usr/local/bin/virtualenvwrapper.sh

#export PATH=$PATH:/Library/PostgreSQL/9.1/bin
export PATH=~/Developer/usr/bin:/usr/local/bin:$PATH
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

[[ -s "/Users/Rawkcy/.rvm/scripts/rvm" ]] && source "/Users/Rawkcy/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
